{
    "catchphrases": [
        "Hamlet",
        "flight plan",
        "alter ego",
        "rat trap",
        "fireworks",
        "hood-wink",
        "masked potatoes",
        "red snapper",
        "human pearls",
        "jelly moulds",
        "nick of time",
        "movie moguls",
        "mechanical marvel",
        "stomach ache",
        "remote control robot",
        "wedding cake",
        "Frankenstein",
        "Hollywood",
        "crystal ball",
        "human collector's item",
        "uncanny photographic mental processes",
        "nerve center",
        "oil factory",
        "reverse polarity",
        "ice skates",
        "complications",
        "hieroglyphics",
        "missing relatives",
        "sudden incapacitation",
        "one track batcomputer mind",
        "Fourth Amendment",
        "heart failure",
        "purple cannibals",
        "understatements",
        "pin cushions",
        "human surfboards",
        "rising headlights",
        "incantation",
        "Robert Louis Stevenson",
        "priceless collection of Etruscan snoods",
        "cold creeps",
        "here we go again",
        "special delivery",
        "return from oblivion",
        "crucial moment",
        "finishing touches",
        "bargain basements",
        "Rip Van Winkle",
        "interplanetary yard stick",
        "rock garden",
        "Jack-in-the-Box",
        "Fourth of July",
        "interruptions",
        "toreador",
        "matador",
        "guacamole",
        "bat-logic",
        "deposit slip",
        "stratosphere",
        "ghost writer",
        "autobon",
        "crack-up",
        "miracle",
        "astronomy",
        "terminology",
        "mashed potatoes",
        "naivete",
        "cliffhangers",
        "sub-orbit",
        "history",
        "catastrophe",
        "cryptology",
        "trampoline",
        "fork in the road",
        "Titanic",
        "hypotheses",
        "bijou",
        "split seconds",
        "olfactory",
        "jetset",
        "tipoff",
        "hamburger",
        "Luthor Burbank",
        "anagrams",
        "haziness",
        "contributing to the delinquency of minors",
        "roadblocks",
        "show-ups",
        "Alps",
        "hamstrings",
        "underwritten metropolis",
        "karats",
        "known flying objects",
        "unknown flying objects",
        "unrefillable prescriptions",
        "giveaways",
        "astringent plum-like fruit",
        "skull tap",
        "ashtray",
        "smoke",
        "haberdashery",
        "lodestone",
        "rainbow",
        "hallelujah",
        "fishbowl",
        "crossfire",
        "red herring",
        "serpentine",
        "bouncing boiler-plated fits",
        "transistors",
        "rats in a trap",
        "alphabet",
        "ball and chain",
        "fruit salad",
        "New Year's Eve",
        "homicide",
        "reincarnation",
        "explosion",
        "helmets",
        "happenstance",
        "switcheroo",
        "ricochet",
        "jackpot",
        "bat-trap",
        "nightmare",
        "Taj Mahal",
        "tee shot",
        "shrinkage",
        "smokestack",
        "camouflage",
        "masquerade",
        "asp",
        "taxadermy",
        "triple feat",
        "kindergarten",
        "Wayne Manor",
        "puzzlers",
        "oxygen",
        "jitterbug",
        "firing squad",
        "Davey Jones",
        "epicure",
        "love birds",
        "bunyons",
        "olee-o",
        "taxation",
        "rocking chair",
        "gunpowder",
        "hairdo",
        "forecast",
        "Motor Von Bon",
        "jawbreaker",
        "sun dial",
        "squirrel cage",
        "hijackers",
        "horseshoes",
        "trasitor's bill",
        "rainbow",
        "fly trap",
        "semantics",
        "recompense",
        "polar front",
        "hijack",
        "tuxedo",
        "shamrocks",
        "distortion",
        "chicken coop",
        "epigrams",
        "travel agent",
        "impossibility",
        "metronome",
        "apparition",
        "perfect pitch",
        "relief",
        "piano",
        "fugitives",
        "fratricide",
        "Caruso",
        "greed",
        "Sherlock Holmes",
        "bank deposits",
        "graft zepplin",
        "voltage",
        "seditives",
        "memory bank",
        "multitudes",
        "sonic booms",
        "holocaust",
        "gambles",
        "cinemascope",
        "miscast",
        "armadilloes",
        "precision",
        "dead end",
        "bankruptcy",
        "madness",
        "stewpot",
        "caffeine",
        "flypaper",
        "unlikelihood",
        "jet set",
        "hoaxes",
        "hostage",
        "agility",
        "blackout",
        "mucelage",
        "timebomb",
        "gemini",
        "eggshells",
        "ten toes",
        "hyperdermics",
        "detonation",
        "gullibility",
        "homework",
        "dilemna",
        "homecoming",
        "tartars",
        "gall",
        "karate",
        "hoofbeats",
        "stuffing",
        "grammar",
        "Koufax",
        "safari",
        "headlines",
        "iceberg",
        "blizzard",
        "snowball",
        "backfire",
        "felony",
        "geography",
        "sewer pipe",
        "Venuzuela",
        "stalactites",
        "trolls and goblins",
        "ordeuvres",
        "jigsaw puzzle",
        "stampede",
        "human pearls",
        "hidal burn",
        "resourcefulness",
        "mush",
        "handiwork",
        "self-service",
        "mermaid",
        "bulls-eye",
        "stereo",
        "shucks",
        "diversionary tactics",
        "Houdini",
        "funny bone",
        "hutzpah",
        "clockwork",
        "hunting horn",
        "Zorro",
        "living end",
        "oversight",
        "floor covering",
        "escape hatch",
        "chillblaines",
        "polar ice sheet",
        "standstills",
        "riot ball",
        "surprise parties",
        "tintanabulation",
        "rising hemlines",
        "levitation",
        "molars",
        "knit one pearl two",
        "slipped disc",
        "mechanical armies",
        "disappearing act",
        "helplessness",
        "human pressure cookers",
        "non-sequiturs",
        "barracuda",
        "showcase",
        "popcorn",
        "hole in a donut",
        "birthday cake",
        "graveyard",
        "schizophrenia",
        "ravioli",
        "conflagration",
        "armour plate",
        "wigs",
        "magician",
        "vacuum",
        "Las Vegas",
        "Benedict Arnold",
        "hailstorms",
        "murder",
        "detonator",
        "Cinderella",
        "tome",
        "trickery",
        "cats",
        "icepicks",
        "knockout drops",
        "hot foot",
        "Romeo and Juliet",
        "iodine",
        "paraffin",
        "spiderwebs",
        "looking glass",
        "impregnability",
        "encore",
        "Golden Gate",
        "hurricane",
        "whiskers",
        "false front",
        "skyrocket",
        "headache",
        "chocolate eclair",
        "fog",
        "rudder",
        "straightjacket",
        "blank cartridge",
        "flip-flop",
        "cliche",
        "weaponry",
        "dart",
        "inquisition",
        "deviltry",
        "Blackbeard",
        "green card",
        "jail break",
        "rheostat",
        "Einstein",
        "high wire",
        "mainframe",
        "corpusles",
        "sarcophagus",
        "cosmos",
        "kilowatts",
        "Bill of Rights",
        "hot spot",
        "IT&T",
        "banks",
        "hypnotism",
        "harem",
        "fate worse than death",
        "hardest metal in the world",
        "journey to the center of the earth",
        "waste of energy",
        "razor's edge",
        "taxidermy",
        "bluebeard",
        "Parefski",
        "heartbreak",
        "vertebra",
        "keyring",
        "keyhole",
        "mesmerism",
        "pseudonym",
        "hydraulics",
        "floodgate"
    ],
    "actions": [
        "aieee",
        "aiieee",
        "awk",
        "awkkkkkk",
        "bam",
        "bang",
        "bang-eth",
        "bap",
        "biff",
        "bloop",
        "blurp",
        "boff",
        "bonk",
        "clange",
        "clank",
        "clank-est",
        "clash",
        "clunk",
        "clunk-eth",
        "cr-r-a-a-ck",
        "crash",
        "crr-aaack",
        "crraack",
        "crunch",
        "crunch-eth",
        "eee-yow",
        "flrbbbbb",
        "glipp",
        "glurpp",
        "kapow",
        "kayo",
        "ker-plop",
        "ker-sploosh",
        "klonk",
        "krunch",
        "ooooff",
        "ouch",
        "ouch-eth",
        "owww",
        "pam",
        "plop",
        "pow",
        "powie",
        "qunckkk",
        "rakkk",
        "rip",
        "slosh",
        "sock",
        "spla-a-t",
        "splatt",
        "sploosh",
        "swa-a-p",
        "swish",
        "swoosh",
        "thunk",
        "thwack",
        "thwacke",
        "thwape",
        "thwapp",
        "touche",
        "uggh",
        "urkk",
        "urkkk",
        "vronk",
        "whack",
        "whack-eth",
        "wham-eth",
        "whamm",
        "whap",
        "z-zwap",
        "zam",
        "zamm",
        "zap",
        "zapeth",
        "zgruppp",
        "zlonk",
        "zlopp",
        "zlott",
        "zok",
        "zowie",
        "zwapp",
        "zzzzzwap"
    ]
}
